#RabbitMQ host
rabbithost=127.0.0.1
#RabbitMQ post
rabbitport=5672
#软交换管理密码 /usr/local/freeswitch/conf/autoload_configs/event_socket.conf.xml
pbxpassword=pbxpasswd@2024
#用户登录令牌密码
jwtpassword=jwtpasswd@2024
#主服务器队列密码 rabbitmqctl change_password pscc xxxx
rabbitpass=rabpasswd@2024

appkey=
accesskeyid=
accesskeyidsecret=
baseurl=http://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/asr